FROM --platform=amd64 python:3.8-slim-buster as base

WORKDIR /app

COPY . /app

RUN sed -i 's|deb.debian.org|mirrors.huaweicloud.com|g' /etc/apt/sources.list && \
    apt-get update && \ 
    apt-get install --no-install-recommends -y gcc build-essential

RUN pip install -r /app/docker_build/cpu/simple_cpu_requirements.txt -i https://mirrors.aliyun.com/pypi/ --no-cache-dir 