FROM --platform=amd64 python:3.8-slim-buster as base

# TODO: add gcc
RUN sed -i 's|deb.debian.org|mirrors.huaweicloud.com|g' /etc/apt/sources.list && \
    apt-get update && \ 
    apt-get install --no-install-recommends -y gcc build-essential


WORKDIR /app
COPY ./docker_build/cpu/cpu_requirements.txt /app


RUN pip install -r /app/cpu_requirements.txt -i https://mirrors.aliyun.com/pypi/ --no-cache-dir 

COPY . /app